//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlisseTonPiedBotDotNet.Modules {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VideoLinkData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoLinkData() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlisseTonPiedBotDotNet.Modules.VideoLinkData", typeof(VideoLinkData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830368477646815272/caffard.mp4.
        /// </summary>
        internal static string videoCafard {
            get {
                return ResourceManager.GetString("videoCafard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830368477646815272/caffard.mp4.
        /// </summary>
        internal static string videoCafard1 {
            get {
                return ResourceManager.GetString("videoCafard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/529121560414650368/830431832704811008/pepite-de-chocolat-swan.mp4.
        /// </summary>
        internal static string videoChocolat {
            get {
                return ResourceManager.GetString("videoChocolat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830368411333951498/Explosion-1.mp4.
        /// </summary>
        internal static string videoExplosion {
            get {
                return ResourceManager.GetString("videoExplosion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/829710528498761758/isgiroud.mp4.
        /// </summary>
        internal static string videoGiroud {
            get {
                return ResourceManager.GetString("videoGiroud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830496016452288552/maskey-masterclass-jacob.mp4.
        /// </summary>
        internal static string videoMasterClass {
            get {
                return ResourceManager.GetString("videoMasterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/529121560414650368/828562443080826900/Muscu.mp4.
        /// </summary>
        internal static string VideoOupa {
            get {
                return ResourceManager.GetString("VideoOupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830429242462306325/axel-vient-manger.mp4.
        /// </summary>
        internal static string videoPutain {
            get {
                return ResourceManager.GetString("videoPutain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://cdn.discordapp.com/attachments/732571903729860695/830368484286136340/yo.mp4.
        /// </summary>
        internal static string videoxd {
            get {
                return ResourceManager.GetString("videoxd", resourceCulture);
            }
        }
    }
}
